# Generated by Django 2.2 on 2023-09-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20230915_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
